# Uncomment the next line to define a global platform for your project
platform :ios, '14.5'

target 'VelocitycubedCapacitorOauth2' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for VelocitycubedCapacitorOauth2
  pod 'Capacitor', :path => '../../node_modules/@capacitor/ios'
  pod 'CapacitorCordova', :path => '../../node_modules/@capacitor/ios'
  pod 'OAuthSwift', :git => 'https://github.com/OAuthSwift/OAuthSwift.git'

end
